version: '3.9'
networks:
  roboshop:
    driver: bridge
services:
  web:
    container_name: web
    image: web:v1
    depends_on:
      - catalogue
      - mongodb
      - user
    ports:
      -80:80
  mongodb: 
    image: mongodb:v1
    container_name: mongodb
  catalogue: 
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  redis: 
    image: redis


  