version: '3.9'
networks:
  roboshop:
    driver: bridge
services:
  web:
    container_name: web
    image: web:v1
    depends_on:
      - catalogue
      - mongodb
      - user
      - cart
      - shipping
    ports:
      - 80:80
  mongodb: 
    image: mongodb:v1
    container_name: mongodb
  catalogue: 
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  redis: 
    image: redis
  cart:
    image: cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue
  mysql: 
    image: mysql:v1
    container_name: mysql
  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
      - mysql


  